[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/youpie/AutoKuma.git?branch=master"]
git = "https://github.com/youpie/AutoKuma.git"
branch = "master"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
